export const blobityOptions = {
  licenseKey: "opensource",
  focusableElementsOffsetX: 8,
  focusableElementsOffsetY: 8,
  // color: "#ff351c",
  dotColor: "#8d7c66",
  invert: true,
  focusableElements:    
    "[data-blobity],[tabindex], a:not([data-no-blobity]), h3:not([data-no-blobity]), li:not([data-no-blobity]) ,button:not([data-no-blobity]), [data-blobity-tooltip]",
  font: "Roboto",
  fontSize: 16,
  fontWeight: 500,
  opacity: 1,
  // fontColor: "#8d7c66",
  zIndex: 100,
  size: 40,
  radius: 4,
  magnetic: true,
  //   kineticMorphing: true,
};
